theme: jekyll-theme-minimal
layout: default
# Setup
title:               John Fink
tagline:             My Personal Website
description:         
url:                 https://jtfink.github.io/
baseurl:             ''
paginate:            5

plugins:          [jekyll-paginate]

# About/contact
author:
  name:              John Fink
  url:               https://jtfink.github.io/
  email:             johnfink@u.boisestate.edu
